Repository clytage/rawon, pull requests merged in 2021-10, with the labels that each got.

#496 feat(music): Search command improvement
  src/commands/music/PlayCommand.ts
  src/commands/music/SearchCommand.ts
  src/config.ts
Labels: enhancement, hacktoberfest-accepted

#500 feat(ServerQueue): add destroy function and delete messages
  src/events/ChannelUpdateEvent.ts
  src/events/VoiceStateUpdateEvent.ts
  src/structures/ServerQueue.ts
  src/utils/handlers/GeneralUtil.ts
Labels: enhancement, feat: v2, feat: player, hacktoberfest-accepted

#501 feat(ServerQueue): adding 'idle' property to check whether the queue is idle or not
  src/events/VoiceStateUpdateEvent.ts
  src/structures/ServerQueue.ts
  src/utils/handlers/GeneralUtil.ts
Labels: enhancement, feat: v2, feat: player, hacktoberfest-accepted

#502 style(*): reduce the usage of 'any' data type
  src/commands/developers/EvalCommand.ts
  src/commands/general/HelpCommand.ts
  src/commands/general/PingCommand.ts
  src/commands/moderation/BanCommand.ts
  src/commands/moderation/KickCommand.ts
  src/commands/moderation/MuteCommand.ts
  src/commands/moderation/UnBanCommand.ts
  src/commands/moderation/UnMuteCommand.ts
  src/commands/moderation/WarnCommand.ts
  src/commands/music/LyricsCommand.ts
  src/commands/music/PauseCommand.ts
  src/commands/music/PlayCommand.ts
  src/commands/music/QueueCommand.ts
  src/commands/music/RepeatCommand.ts
  src/commands/music/ResumeCommand.ts
  src/commands/music/SearchCommand.ts
  src/commands/music/ShuffleCommand.ts
  src/commands/music/SkipToCommand.ts
  src/commands/music/StayInQueueCommand.ts
  src/commands/music/StopCommand.ts
  src/commands/music/VolumeCommand.ts
  src/events/InteractionCreateEvent.ts
  src/events/MessageCreateEvent.ts
  src/events/VoiceStateUpdateEvent.ts
  src/structures/BaseCommand.ts
  src/structures/CommandContext.ts
  src/typings/index.d.ts
  src/utils/ButtonPagination.ts
  src/utils/CommandManager.ts
  src/utils/decorators/Inhibit.ts
  src/utils/decorators/MusicUtil.ts
  src/utils/handlers/GeneralUtil.ts
Labels: enhancement, feat: v2, hacktoberfest-accepted

#499 fix(VoiceStateUpdateEvent): timeout fix
  src/events/VoiceStateUpdateEvent.ts
Labels: help wanted, hacktoberfest-accepted
